//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class dK
    {
        public dK()
        {
            this.dMays = new HashSet<dMay>();
            this.dusers = new HashSet<duser>();
            this.pCs = new HashSet<pC>();
            this.pCs1 = new HashSet<pC>();
            this.pNs = new HashSet<pN>();
            this.pNCs = new HashSet<pNC>();
            this.pSDs = new HashSet<pSD>();
            this.pTBs = new HashSet<pTB>();
            this.pTons = new HashSet<pTon>();
        }
    
        public int kid { get; set; }
        public string kten { get; set; }
        public string diachi { get; set; }
    
        public virtual ICollection<dMay> dMays { get; set; }
        public virtual ICollection<duser> dusers { get; set; }
        public virtual ICollection<pC> pCs { get; set; }
        public virtual ICollection<pC> pCs1 { get; set; }
        public virtual ICollection<pN> pNs { get; set; }
        public virtual ICollection<pNC> pNCs { get; set; }
        public virtual ICollection<pSD> pSDs { get; set; }
        public virtual ICollection<pTB> pTBs { get; set; }
        public virtual ICollection<pTon> pTons { get; set; }
    }
}
