//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class dK
    {
        public dK()
        {
            this.dMay = new HashSet<dMay>();
            this.duser = new HashSet<duser>();
            this.pC = new HashSet<pC>();
            this.pC1 = new HashSet<pC>();
            this.pN = new HashSet<pN>();
            this.pNC = new HashSet<pNC>();
            this.pSD = new HashSet<pSD>();
            this.pTB = new HashSet<pTB>();
        }
    
        public int kid { get; set; }
        public string kten { get; set; }
        public string diachi { get; set; }
    
        public virtual ICollection<dMay> dMay { get; set; }
        public virtual ICollection<duser> duser { get; set; }
        public virtual ICollection<pC> pC { get; set; }
        public virtual ICollection<pC> pC1 { get; set; }
        public virtual ICollection<pN> pN { get; set; }
        public virtual ICollection<pNC> pNC { get; set; }
        public virtual ICollection<pSD> pSD { get; set; }
        public virtual ICollection<pTB> pTB { get; set; }
    }
}
