//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class dKH
    {
        public dKH()
        {
            this.pNCT = new HashSet<pNCT>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
    
        public virtual ICollection<pNCT> pNCT { get; set; }
    }
}
