//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class dMay
    {
        public dMay()
        {
            this.pSDCTs = new HashSet<pSDCT>();
        }
    
        public int id { get; set; }
        public string maso { get; set; }
        public string tenmay { get; set; }
        public Nullable<int> kid { get; set; }
    
        public virtual dK dK { get; set; }
        public virtual ICollection<pSDCT> pSDCTs { get; set; }
    }
}
