//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class dNVT
    {
        public dNVT()
        {
            this.dVT = new HashSet<dVT>();
        }
    
        public int nvtid { get; set; }
        public string tennhom { get; set; }
    
        public virtual ICollection<dVT> dVT { get; set; }
    }
}
