//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class dVT
    {
        public dVT()
        {
            this.dQCCT = new HashSet<dQCCT>();
            this.pCCT = new HashSet<pCCT>();
            this.pNCCT = new HashSet<pNCCT>();
            this.pNCT = new HashSet<pNCT>();
            this.pSDCT = new HashSet<pSDCT>();
        }
    
        public int vid { get; set; }
        public string dvt1 { get; set; }
        public Nullable<int> nvtid { get; set; }
        public string vTen { get; set; }
        public Nullable<double> giathanh { get; set; }
        public Nullable<int> isupdate { get; set; }
        public string mavt { get; set; }
        public Nullable<int> iddvt { get; set; }
    
        public virtual dDVT dDVT { get; set; }
        public virtual dNVT dNVT { get; set; }
        public virtual ICollection<dQCCT> dQCCT { get; set; }
        public virtual ICollection<pCCT> pCCT { get; set; }
        public virtual ICollection<pNCCT> pNCCT { get; set; }
        public virtual ICollection<pNCT> pNCT { get; set; }
        public virtual ICollection<pSDCT> pSDCT { get; set; }
    }
}
