//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class dVT
    {
        public dVT()
        {
            this.dQCCTs = new HashSet<dQCCT>();
            this.pCCTs = new HashSet<pCCT>();
            this.pNCCTs = new HashSet<pNCCT>();
            this.pNCTs = new HashSet<pNCT>();
            this.pSDCTs = new HashSet<pSDCT>();
            this.pTons = new HashSet<pTon>();
        }
    
        public int vid { get; set; }
        public string dvt1 { get; set; }
        public Nullable<int> nvtid { get; set; }
        public string vTen { get; set; }
        public Nullable<double> giathanh { get; set; }
        public Nullable<int> isupdate { get; set; }
        public string mavt { get; set; }
        public Nullable<int> iddvt { get; set; }
    
        public virtual dDVT dDVT { get; set; }
        public virtual dNVT dNVT { get; set; }
        public virtual ICollection<dQCCT> dQCCTs { get; set; }
        public virtual ICollection<pCCT> pCCTs { get; set; }
        public virtual ICollection<pNCCT> pNCCTs { get; set; }
        public virtual ICollection<pNCT> pNCTs { get; set; }
        public virtual ICollection<pSDCT> pSDCTs { get; set; }
        public virtual ICollection<pTon> pTons { get; set; }
    }
}
