//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class pC
    {
        public pC()
        {
            this.pCCT = new HashSet<pCCT>();
        }
    
        public int cid { get; set; }
        public DateTime pdate { get; set; }
        public Nullable<int> pfrom { get; set; }
        public Nullable<int> pto { get; set; }
        public string cmaso { get; set; }
    
        public virtual dK dK { get; set; }
        public virtual dK dK1 { get; set; }
        public virtual ICollection<pCCT> pCCT { get; set; }
    }
}
