//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class pN
    {
        public pN()
        {
            this.pNCTs = new HashSet<pNCT>();
        }
    
        public int nid { get; set; }
        public Nullable<System.DateTime> ndate { get; set; }
        public Nullable<int> kid { get; set; }
        public string nmaso { get; set; }
        public DateTime ngayhd { get; set; }
        public Nullable<int> isupdate { get; set; }
    
        public virtual dK dK { get; set; }
        public virtual ICollection<pNCT> pNCTs { get; set; }
    }
}
