//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class pNC
    {
        public pNC()
        {
            this.pNCCT = new HashSet<pNCCT>();
        }
    
        public int ncid { get; set; }
        public Nullable<System.DateTime> ncdate { get; set; }
        public Nullable<int> kid { get; set; }
        public Nullable<System.DateTime> tgcan { get; set; }
        public string mucdich { get; set; }
        public string maso { get; set; }
        public Nullable<int> isgui { get; set; }
    
        public virtual dK dK { get; set; }
        public virtual ICollection<pNCCT> pNCCT { get; set; }
    }
}
