//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class pNCCT
    {
        public int ncctid { get; set; }
        public Nullable<int> ncid { get; set; }
        public Nullable<int> vid { get; set; }
        public Nullable<double> ncsoluong { get; set; }
        public string diengiai { get; set; }
    
        public virtual dVT dVT { get; set; }
        public virtual pNC pNC { get; set; }
    }
}
