//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class pNCT
    {
        public int nctid { get; set; }
        public Nullable<int> vid { get; set; }
        public Nullable<double> nctsoluong { get; set; }
        public Nullable<int> nid { get; set; }
        public Nullable<int> idKH { get; set; }
        public Nullable<double> giathanh { get; set; }
        public Nullable<int> dvt { get; set; }
    
        public virtual dDVT dDVT { get; set; }
        public virtual dKH dKH { get; set; }
        public virtual dVT dVT1 { get; set; }
        public virtual pN pN { get; set; }
    }
}
