//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class pSD
    {
        public pSD()
        {
            this.pSDCT = new HashSet<pSDCT>();
        }
    
        public int sdid { get; set; }
        public Nullable<System.DateTime> sdate { get; set; }
        public Nullable<int> kid { get; set; }
        public string smaso { get; set; }
    
        public virtual dK dK { get; set; }
        public virtual ICollection<pSDCT> pSDCT { get; set; }
    }
}
