//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho
{
    using System;
    using System.Collections.Generic;
    
    public partial class pSDCT
    {
        public int sdctid { get; set; }
        public Nullable<int> vid { get; set; }
        public Nullable<double> sdctsoluong { get; set; }
        public Nullable<int> sdid { get; set; }
        public string diengiai { get; set; }
        public Nullable<int> mid { get; set; }
        public Nullable<double> hansudung { get; set; }
        public Nullable<double> dongia { get; set; }
        public Nullable<int> iddvt { get; set; }
    
        public virtual dDVT dDVT { get; set; }
        public virtual dMay dMay { get; set; }
        public virtual dVT dVT { get; set; }
        public virtual pSD pSD { get; set; }
    }
}
